// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ScalpayApi.Data;
using ScalpayApi.Enums;
using System;

namespace ScalpayApi.Migrations
{
    [DbContext(typeof(ScalpayDbContext))]
    partial class ScalpayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("ScalpayApi.Models.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ArgsString")
                        .IsRequired()
                        .HasColumnName("Args");

                    b.Property<int>("AuditType");

                    b.Property<DateTime>("InsertTime")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ItemKey");

                    b.Property<string>("Operator");

                    b.Property<string>("ProjectKey");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.ToTable("Audits");
                });

            modelBuilder.Entity("ScalpayApi.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DefaultResultString")
                        .IsRequired()
                        .HasColumnName("DefaultResult");

                    b.Property<string>("Description");

                    b.Property<DateTime>("InsertTime")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsLatest");

                    b.Property<string>("ItemKey")
                        .IsRequired();

                    b.Property<int>("Mode");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("ParameterInfosString")
                        .IsRequired()
                        .HasColumnName("ParameterInfos");

                    b.Property<string>("ProjectKey");

                    b.Property<int>("ResultDataType");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("ScalpayApi.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<DateTime>("InsertTime")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsLatest");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("ProjectKey")
                        .IsRequired();

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ScalpayApi.Models.Rule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConditionString")
                        .IsRequired()
                        .HasColumnName("Condition");

                    b.Property<DateTime>("InsertTime")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ItemId");

                    b.Property<int>("Order");

                    b.Property<string>("ResultString")
                        .IsRequired()
                        .HasColumnName("Result");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Rule");
                });

            modelBuilder.Entity("ScalpayApi.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApiKey")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FullName")
                        .IsRequired();

                    b.Property<DateTime>("InsertTime")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<int>("PrivilegesInt")
                        .HasColumnName("Privileges");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ScalpayApi.Models.Rule", b =>
                {
                    b.HasOne("ScalpayApi.Models.Item", "Item")
                        .WithMany("Rules")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
